[project]
name = "multi-agent-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ddgs>=9.9.2",
    "google-adk>=1.20.0",
    "litellm>=1.80.7",
    "beautifulsoup4>=4.14.3",
    "requests>=2.32.5",
]
